// timezoneAbbrevs.js — timezone acronyms -> IANA zones, for Father Time.
//
// Each row: [ABBR, full name, IANA zone, kind]
//   kind "std" = names the standard (winter) half of a DST zone
//   kind "dst" = names the daylight (summer) half
//   kind "any" = generic, or the zone has no DST
//
// An acronym maps to the REGION that uses it, not a frozen offset: people
// say "2pm EST" all summer and mean Eastern time as it is actually observed.
// The converter notes when the typed half isn't the one in effect.
//
// Several acronyms are claimed by more than one region (CST, IST, BST, AST,
// PST...). The first row for an acronym wins the short form; every row's
// full name still resolves, so "china standard time" or "irish standard
// time" reach the others.

export const ZONE_ABBREVS = [
  // ── Universal ──
  ["UTC", "Coordinated Universal Time", "UTC", "any"],
  ["GMT", "Greenwich Mean Time", "UTC", "any"],
  ["Z", "Zulu Time", "UTC", "any"],
  ["AoE", "Anywhere on Earth", "Etc/GMT+12", "any"],

  // ── Shared acronyms: listed early so the most-used meaning wins ──
  ["IST", "India Standard Time", "Asia/Kolkata", "any"],
  ["GST", "Gulf Standard Time", "Asia/Dubai", "any"],

  // ── North America ──
  ["NST", "Newfoundland Standard Time", "America/St_Johns", "std"],
  ["NDT", "Newfoundland Daylight Time", "America/St_Johns", "dst"],
  ["NT", "Newfoundland Time", "America/St_Johns", "any"],
  ["AST", "Atlantic Standard Time", "America/Halifax", "std"],
  ["ADT", "Atlantic Daylight Time", "America/Halifax", "dst"],
  ["AT", "Atlantic Time", "America/Halifax", "any"],
  ["EST", "Eastern Standard Time", "America/New_York", "std"],
  ["EDT", "Eastern Daylight Time", "America/New_York", "dst"],
  ["ET", "Eastern Time", "America/New_York", "any"],
  ["CST", "Central Standard Time", "America/Chicago", "std"],
  ["CDT", "Central Daylight Time", "America/Chicago", "dst"],
  ["CT", "Central Time", "America/Chicago", "any"],
  ["MST", "Mountain Standard Time", "America/Denver", "std"],
  ["MDT", "Mountain Daylight Time", "America/Denver", "dst"],
  ["MT", "Mountain Time", "America/Denver", "any"],
  ["PST", "Pacific Standard Time", "America/Los_Angeles", "std"],
  ["PDT", "Pacific Daylight Time", "America/Los_Angeles", "dst"],
  ["PT", "Pacific Time", "America/Los_Angeles", "any"],
  ["AKST", "Alaska Standard Time", "America/Anchorage", "std"],
  ["AKDT", "Alaska Daylight Time", "America/Anchorage", "dst"],
  ["AKT", "Alaska Time", "America/Anchorage", "any"],
  ["HST", "Hawaii Standard Time", "Pacific/Honolulu", "any"],
  ["HAST", "Hawaii-Aleutian Standard Time", "America/Adak", "std"],
  ["HADT", "Hawaii-Aleutian Daylight Time", "America/Adak", "dst"],
  ["HDT", "Hawaii-Aleutian Daylight Time", "America/Adak", "dst"],
  ["PMST", "Pierre & Miquelon Standard Time", "America/Miquelon", "std"],
  ["PMDT", "Pierre & Miquelon Daylight Time", "America/Miquelon", "dst"],
  ["WGT", "West Greenland Time", "America/Nuuk", "std"],
  ["WGST", "West Greenland Summer Time", "America/Nuuk", "dst"],
  ["EGT", "East Greenland Time", "America/Scoresbysund", "std"],
  ["EGST", "East Greenland Summer Time", "America/Scoresbysund", "dst"],
  ["CST", "Cuba Standard Time", "America/Havana", "std"],

  // ── Central & South America ──
  ["BRT", "Brasília Time", "America/Sao_Paulo", "any"],
  ["BRST", "Brasília Summer Time", "America/Sao_Paulo", "any"],
  ["AMT", "Amazon Time", "America/Manaus", "any"],
  ["ACT", "Acre Time", "America/Rio_Branco", "any"],
  ["FNT", "Fernando de Noronha Time", "America/Noronha", "any"],
  ["ART", "Argentina Time", "America/Argentina/Buenos_Aires", "any"],
  ["CLT", "Chile Standard Time", "America/Santiago", "std"],
  ["CLST", "Chile Summer Time", "America/Santiago", "dst"],
  ["EAST", "Easter Island Standard Time", "Pacific/Easter", "std"],
  ["EASST", "Easter Island Summer Time", "Pacific/Easter", "dst"],
  ["PET", "Peru Time", "America/Lima", "any"],
  ["COT", "Colombia Time", "America/Bogota", "any"],
  ["VET", "Venezuela Time", "America/Caracas", "any"],
  ["ECT", "Ecuador Time", "America/Guayaquil", "any"],
  ["GALT", "Galápagos Time", "Pacific/Galapagos", "any"],
  ["BOT", "Bolivia Time", "America/La_Paz", "any"],
  ["UYT", "Uruguay Time", "America/Montevideo", "any"],
  ["PYT", "Paraguay Time", "America/Asuncion", "any"],
  ["PYST", "Paraguay Summer Time", "America/Asuncion", "any"],
  ["GYT", "Guyana Time", "America/Guyana", "any"],
  ["SRT", "Suriname Time", "America/Paramaribo", "any"],
  ["GFT", "French Guiana Time", "America/Cayenne", "any"],
  ["FKT", "Falkland Islands Time", "Atlantic/Stanley", "any"],
  ["FKST", "Falkland Islands Summer Time", "Atlantic/Stanley", "any"],
  ["GST", "South Georgia Time", "Atlantic/South_Georgia", "any"],

  // ── Europe & Atlantic ──
  ["WET", "Western European Time", "Europe/Lisbon", "std"],
  ["WEST", "Western European Summer Time", "Europe/Lisbon", "dst"],
  ["BST", "British Summer Time", "Europe/London", "dst"],
  ["IST", "Irish Standard Time", "Europe/Dublin", "dst"],
  ["CET", "Central European Time", "Europe/Paris", "std"],
  ["CEST", "Central European Summer Time", "Europe/Paris", "dst"],
  ["MET", "Middle European Time", "Europe/Berlin", "std"],
  ["MEST", "Middle European Summer Time", "Europe/Berlin", "dst"],
  ["EET", "Eastern European Time", "Europe/Athens", "std"],
  ["EEST", "Eastern European Summer Time", "Europe/Athens", "dst"],
  ["FET", "Further-Eastern European Time", "Europe/Minsk", "any"],
  ["MSK", "Moscow Standard Time", "Europe/Moscow", "any"],
  ["TRT", "Turkey Time", "Europe/Istanbul", "any"],
  ["SAMT", "Samara Time", "Europe/Samara", "any"],
  ["AZOT", "Azores Time", "Atlantic/Azores", "std"],
  ["AZOST", "Azores Summer Time", "Atlantic/Azores", "dst"],
  ["CVT", "Cape Verde Time", "Atlantic/Cape_Verde", "any"],

  // ── Africa & Indian Ocean ──
  ["WAT", "West Africa Time", "Africa/Lagos", "any"],
  ["CAT", "Central Africa Time", "Africa/Maputo", "any"],
  ["EAT", "East Africa Time", "Africa/Nairobi", "any"],
  ["SAST", "South Africa Standard Time", "Africa/Johannesburg", "any"],
  ["MUT", "Mauritius Time", "Indian/Mauritius", "any"],
  ["SCT", "Seychelles Time", "Indian/Mahe", "any"],
  ["RET", "Réunion Time", "Indian/Reunion", "any"],
  ["IOT", "Indian Ocean Time", "Indian/Chagos", "any"],
  ["MVT", "Maldives Time", "Indian/Maldives", "any"],
  ["TFT", "French Southern & Antarctic Time", "Indian/Kerguelen", "any"],
  ["CCT", "Cocos Islands Time", "Indian/Cocos", "any"],
  ["CXT", "Christmas Island Time", "Indian/Christmas", "any"],

  // ── Middle East, Caucasus & Central Asia ──
  ["IST", "Israel Standard Time", "Asia/Jerusalem", "std"],
  ["IDT", "Israel Daylight Time", "Asia/Jerusalem", "dst"],
  ["AST", "Arabia Standard Time", "Asia/Riyadh", "any"],
  ["IRST", "Iran Standard Time", "Asia/Tehran", "any"],
  ["IRDT", "Iran Daylight Time", "Asia/Tehran", "any"],
  ["GET", "Georgia Standard Time", "Asia/Tbilisi", "any"],
  ["AZT", "Azerbaijan Time", "Asia/Baku", "any"],
  ["AMT", "Armenia Time", "Asia/Yerevan", "any"],
  ["AFT", "Afghanistan Time", "Asia/Kabul", "any"],
  ["PKT", "Pakistan Standard Time", "Asia/Karachi", "any"],
  ["UZT", "Uzbekistan Time", "Asia/Tashkent", "any"],
  ["TMT", "Turkmenistan Time", "Asia/Ashgabat", "any"],
  ["TJT", "Tajikistan Time", "Asia/Dushanbe", "any"],
  ["KGT", "Kyrgyzstan Time", "Asia/Bishkek", "any"],
  ["ALMT", "Alma-Ata Time", "Asia/Almaty", "any"],
  ["YEKT", "Yekaterinburg Time", "Asia/Yekaterinburg", "any"],
  ["OMST", "Omsk Time", "Asia/Omsk", "any"],
  ["NOVT", "Novosibirsk Time", "Asia/Novosibirsk", "any"],
  ["KRAT", "Krasnoyarsk Time", "Asia/Krasnoyarsk", "any"],
  ["IRKT", "Irkutsk Time", "Asia/Irkutsk", "any"],
  ["YAKT", "Yakutsk Time", "Asia/Yakutsk", "any"],
  ["VLAT", "Vladivostok Time", "Asia/Vladivostok", "any"],
  ["SAKT", "Sakhalin Time", "Asia/Sakhalin", "any"],
  ["MAGT", "Magadan Time", "Asia/Magadan", "any"],
  ["SRET", "Srednekolymsk Time", "Asia/Srednekolymsk", "any"],
  ["PETT", "Kamchatka Time", "Asia/Kamchatka", "any"],
  ["ANAT", "Anadyr Time", "Asia/Anadyr", "any"],

  // ── South, East & Southeast Asia ──
  ["NPT", "Nepal Time", "Asia/Kathmandu", "any"],
  ["BTT", "Bhutan Time", "Asia/Thimphu", "any"],
  ["BST", "Bangladesh Standard Time", "Asia/Dhaka", "any"],
  ["SLST", "Sri Lanka Standard Time", "Asia/Colombo", "any"],
  ["MMT", "Myanmar Time", "Asia/Yangon", "any"],
  ["ICT", "Indochina Time", "Asia/Bangkok", "any"],
  ["WIB", "Western Indonesia Time", "Asia/Jakarta", "any"],
  ["WITA", "Central Indonesia Time", "Asia/Makassar", "any"],
  ["WIT", "Eastern Indonesia Time", "Asia/Jayapura", "any"],
  ["MYT", "Malaysia Time", "Asia/Kuala_Lumpur", "any"],
  ["SGT", "Singapore Time", "Asia/Singapore", "any"],
  ["BNT", "Brunei Time", "Asia/Brunei", "any"],
  ["PHT", "Philippine Time", "Asia/Manila", "any"],
  ["PST", "Philippine Standard Time", "Asia/Manila", "any"],
  ["HKT", "Hong Kong Time", "Asia/Hong_Kong", "any"],
  ["CST", "China Standard Time", "Asia/Shanghai", "any"],
  ["TWT", "Taiwan Time", "Asia/Taipei", "any"],
  ["ULAT", "Ulaanbaatar Time", "Asia/Ulaanbaatar", "any"],
  ["HOVT", "Hovd Time", "Asia/Hovd", "any"],
  ["KST", "Korea Standard Time", "Asia/Seoul", "any"],
  ["JST", "Japan Standard Time", "Asia/Tokyo", "any"],
  ["TLT", "Timor-Leste Time", "Asia/Dili", "any"],

  // ── Australia & New Zealand ──
  ["AWST", "Australian Western Standard Time", "Australia/Perth", "any"],
  ["ACWST", "Australian Central Western Time", "Australia/Eucla", "any"],
  ["ACST", "Australian Central Standard Time", "Australia/Adelaide", "std"],
  ["ACDT", "Australian Central Daylight Time", "Australia/Adelaide", "dst"],
  ["AEST", "Australian Eastern Standard Time", "Australia/Sydney", "std"],
  ["AEDT", "Australian Eastern Daylight Time", "Australia/Sydney", "dst"],
  ["AET", "Australian Eastern Time", "Australia/Sydney", "any"],
  ["LHST", "Lord Howe Standard Time", "Australia/Lord_Howe", "std"],
  ["LHDT", "Lord Howe Daylight Time", "Australia/Lord_Howe", "dst"],
  ["NFT", "Norfolk Island Time", "Pacific/Norfolk", "any"],
  ["NZST", "New Zealand Standard Time", "Pacific/Auckland", "std"],
  ["NZDT", "New Zealand Daylight Time", "Pacific/Auckland", "dst"],
  ["NZT", "New Zealand Time", "Pacific/Auckland", "any"],
  ["CHAST", "Chatham Standard Time", "Pacific/Chatham", "std"],
  ["CHADT", "Chatham Daylight Time", "Pacific/Chatham", "dst"],

  // ── Pacific ──
  ["ChST", "Chamorro Standard Time", "Pacific/Guam", "any"],
  ["PGT", "Papua New Guinea Time", "Pacific/Port_Moresby", "any"],
  ["SBT", "Solomon Islands Time", "Pacific/Guadalcanal", "any"],
  ["NCT", "New Caledonia Time", "Pacific/Noumea", "any"],
  ["VUT", "Vanuatu Time", "Pacific/Efate", "any"],
  ["FJT", "Fiji Time", "Pacific/Fiji", "any"],
  ["TVT", "Tuvalu Time", "Pacific/Funafuti", "any"],
  ["GILT", "Gilbert Islands Time", "Pacific/Tarawa", "any"],
  ["MHT", "Marshall Islands Time", "Pacific/Majuro", "any"],
  ["NRT", "Nauru Time", "Pacific/Nauru", "any"],
  ["KOST", "Kosrae Time", "Pacific/Kosrae", "any"],
  ["PONT", "Pohnpei Time", "Pacific/Pohnpei", "any"],
  ["CHUT", "Chuuk Time", "Pacific/Chuuk", "any"],
  ["PWT", "Palau Time", "Pacific/Palau", "any"],
  ["WAKT", "Wake Island Time", "Pacific/Wake", "any"],
  ["TOT", "Tonga Time", "Pacific/Tongatapu", "any"],
  ["WST", "West Samoa Time", "Pacific/Apia", "any"],
  ["SST", "Samoa Standard Time", "Pacific/Pago_Pago", "any"],
  ["TKT", "Tokelau Time", "Pacific/Fakaofo", "any"],
  ["PHOT", "Phoenix Islands Time", "Pacific/Kanton", "any"],
  ["LINT", "Line Islands Time", "Pacific/Kiritimati", "any"],
  ["NUT", "Niue Time", "Pacific/Niue", "any"],
  ["CKT", "Cook Islands Time", "Pacific/Rarotonga", "any"],
  ["TAHT", "Tahiti Time", "Pacific/Tahiti", "any"],
  ["MART", "Marquesas Time", "Pacific/Marquesas", "any"],
  ["GAMT", "Gambier Time", "Pacific/Gambier", "any"],
  ["PST", "Pitcairn Standard Time", "Pacific/Pitcairn", "any"],
];
